# --- Configuración de raspado (scrape_configs) ---
scrape_configs:
  # Job para tu API NestJS
  - job_name: 'nestjs_api' # Un nombre para identificar esta fuente de métricas (tu API)
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ['hz-api:3001'] # La IP y el puerto de tu API en el HOST Ubuntu
    metrics_path: /metrics # La ruta donde tu API NestJS expone las métricas
    honor_labels: true # Permite que tu app provea etiquetas ya predefinidasx
